apiVersion: v1
kind: Service
metadata:
  name: abelup-backend
  namespace: default
  labels:
    app: abelup-backend
spec:
  selector:
    app: abelup-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
